export const plans = [
    {
      "id": 1,
      "provider": "BlueCross",
      "type": "Health",
      "price": 150,
      "coverage": "Basic health coverage including prescriptions and emergency visits",
      "region": "ON",
      "rating": 4.5,
      "term": "1 year",
      "benefits": ["Prescription Coverage", "Emergency Services"],
      "cashback": 10,
      "icon": "https://example.com/logos/bluecross.png",
      "url": "https://www.bluecross.ca"
    },
    {
      "id": 2,
      "provider": "Sun Life",
      "type": "Life",
      "price": 200,
      "coverage": "Life insurance with accidental death coverage",
      "region": "BC",
      "rating": 4.7,
      "term": "5 years",
      "benefits": ["Accidental Death", "Terminal Illness"],
      "cashback": 15,
      "icon": "https://example.com/logos/sunlife.png",
      "url": "https://www.sunlife.ca"
    },
    {
      "id": 3,
      "provider": "ICBC",
      "type": "Auto",
      "price": 120,
      "coverage": "Basic Autoplan mandatory coverage: third-party liability, accident benefits, underinsured motorist protection, vehicle damage",
      "region": "BC",
      "rating": 4.3,
      "term": "1 year",
      "benefits": ["Third-Party Liability", "Accident Benefits", "Vehicle Damage"],
      "cashback": 0,
      "icon": "https://example.com/logos/icbc.png",
      "url": "https://www.icbc.com"
    },
    {
      "id": 4,
      "provider": "BCAA",
      "type": "Auto",
      "price": 90,
      "coverage": "Optional car insurance supplementing Basic Autoplan",
      "region": "BC",
      "rating": 4.4,
      "term": "1 year",
      "benefits": ["Theft Protection", "Collision Damage", "Family Discounts"],
      "cashback": 5,
      "icon": "https://example.com/logos/bcaa.png",
      "url": "https://www.bcaa.com/insurance/car"
    },
    {
      "id": 5,
      "provider": "Reliance Insurance",
      "type": "Auto",
      "price": 100,
      "coverage": "Optional coverage for BC cars via private insurers",
      "region": "BC",
      "rating": 4.2,
      "term": "1 year",
      "benefits": ["Collision", "Theft", "Liability"],
      "cashback": 5,
      "icon": "https://example.com/logos/reliance.png",
      "url": "https://reliance.ca/auto-insurance/private-auto"
    },
    {
      "id": 6,
      "provider": "Manulife",
      "type": "Health",
      "price": 180,
      "coverage": "Extended health coverage including dental, vision, and prescriptions",
      "region": "AB",
      "rating": 4.6,
      "term": "1 year",
      "benefits": ["Dental", "Vision", "Prescription Coverage", "Emergency Services"],
      "cashback": 15,
      "icon": "https://example.com/logos/manulife.png",
      "url": "https://www.manulife.ca/en/insurance/health.html"
    },
    {
      "id": 7,
      "provider": "Intact Insurance",
      "type": "Home",
      "price": 95,
      "coverage": "Home insurance including fire, theft, and natural disasters",
      "region": "ON",
      "rating": 4.4,
      "term": "1 year",
      "benefits": ["Fire Protection", "Theft Coverage", "Natural Disasters"],
      "cashback": 10,
      "icon": "https://example.com/logos/intact.png",
      "url": "https://www.intact.ca"
    },
    {
      "id": 8,
      "provider": "RBC Insurance",
      "type": "Auto",
      "price": 130,
      "coverage": "Third-party liability and collision coverage",
      "region": "MB",
      "rating": 4.2,
      "term": "1 year",
      "benefits": ["Liability", "Collision", "Accident Coverage"],
      "cashback": 10,
      "icon": "https://example.com/logos/rbc.png",
      "url": "https://www.rbcinsurance.com"
    },
    {
      "id": 9,
      "provider": "Desjardins",
      "type": "Life",
      "price": 210,
      "coverage": "Life insurance with critical illness coverage",
      "region": "QC",
      "rating": 4.5,
      "term": "5 years",
      "benefits": ["Critical Illness", "Terminal Illness"],
      "cashback": 12,
      "icon": "https://example.com/logos/desjardins.png",
      "url": "https://www.desjardins.com"
    },
    {
      "id": 10,
      "provider": "Westland Insurance",
      "type": "Auto",
      "price": 110,
      "coverage": "Optional coverage for BC cars, includes Family Autocover package",
      "region": "BC",
      "rating": 4.3,
      "term": "1 year",
      "benefits": ["Collision", "Theft", "Family Package"],
      "cashback": 8,
      "icon": "https://example.com/logos/westland.png",
      "url": "https://www.westlandinsurance.ca/auto/car-insurance/bc"
    },
    {
      "id": 11,
      "provider": "Co-operators",
      "type": "Home",
      "price": 100,
      "coverage": "Comprehensive home coverage with natural disaster protection",
      "region": "AB",
      "rating": 4.5,
      "term": "1 year",
      "benefits": ["Fire", "Theft", "Natural Disasters"],
      "cashback": 10,
      "icon": "https://example.com/logos/cooperators.png",
      "url": "https://www.cooperators.ca"
    },
    {
      "id": 12,
      "provider": "Travel Guard",
      "type": "Travel",
      "price": 50,
      "coverage": "Travel insurance for international trips including medical emergencies",
      "region": "ON",
      "rating": 4.3,
      "term": "1 month",
      "benefits": ["Medical Emergencies", "Trip Cancellation", "Lost Luggage"],
      "cashback": 5,
      "icon": "https://example.com/logos/travelguard.png",
      "url": "https://www.travelguard.ca"
    },
    {
      "id": 13,
      "provider": "Empire Life",
      "type": "Life",
      "price": 195,
      "coverage": "Term life insurance with optional accidental death benefit",
      "region": "NS",
      "rating": 4.4,
      "term": "5 years",
      "benefits": ["Accidental Death", "Terminal Illness"],
      "cashback": 10,
      "icon": "https://example.com/logos/empire.png",
      "url": "https://www.empire.ca"
    },
    {
      "id": 14,
      "provider": "Manulife",
      "type": "Travel",
      "price": 60,
      "coverage": "Travel insurance covering medical and trip interruption",
      "region": "QC",
      "rating": 4.5,
      "term": "1 month",
      "benefits": ["Medical", "Trip Cancellation", "Baggage Loss"],
      "cashback": 5,
      "icon": "https://example.com/logos/manulife.png",
      "url": "https://www.manulife.ca/en/insurance/travel.html"
    },
    {
      "id": 15,
      "provider": "Intact Insurance",
      "type": "Home",
      "price": 90,
      "coverage": "Home insurance covering fire, theft, and water damage",
      "region": "MB",
      "rating": 4.3,
      "term": "1 year",
      "benefits": ["Fire", "Theft", "Water Damage"],
      "cashback": 8,
      "icon": "https://example.com/logos/intact.png",
      "url": "https://www.intact.ca"
    },
    {
      "id": 16,
      "provider": "BCAA",
      "type": "Auto",
      "price": 85,
      "coverage": "Optional auto coverage supplementing BC Basic Autoplan",
      "region": "BC",
      "rating": 4.4,
      "term": "1 year",
      "benefits": ["Collision", "Theft", "Family Discount"],
      "cashback": 5,
      "icon": "https://example.com/logos/bcaa.png",
      "url": "https://www.bcaa.com/insurance/car"
    },
    {
      "id": 17,
      "provider": "Sun Life",
      "type": "Life",
      "price": 205,
      "coverage": "Life insurance with optional critical illness rider",
      "region": "ON",
      "rating": 4.6,
      "term": "5 years",
      "benefits": ["Critical Illness", "Accidental Death"],
      "cashback": 10,
      "icon": "https://example.com/logos/sunlife.png",
      "url": "https://www.sunlife.ca"
    },
    {
      "id": 18,
      "provider": "Westland Insurance",
      "type": "Auto",
      "price": 100,
      "coverage": "Optional BC car insurance with Family Autocover",
      "region": "BC",
      "rating": 4.3,
      "term": "1 year",
      "benefits": ["Collision", "Theft", "Family Package"],
      "cashback": 7,
      "icon": "https://example.com/logos/westland.png",
      "url": "https://www.westlandinsurance.ca/auto/car-insurance/bc"
    },
    {
      "id": 19,
      "provider": "Co-operators",
      "type": "Home",
      "price": 105,
      "coverage": "Comprehensive home coverage with natural disaster protection",
      "region": "NB",
      "rating": 4.4,
      "term": "1 year",
      "benefits": ["Fire", "Theft", "Natural Disasters"],
      "cashback": 9,
      "icon": "https://example.com/logos/cooperators.png",
      "url": "https://www.cooperators.ca"
    },
    {
      "id": 20,
      "provider": "Travel Guard",
      "type": "Travel",
      "price": 55,
      "coverage": "Travel insurance covering medical emergencies and lost baggage",
      "region": "AB",
      "rating": 4.2,
      "term": "1 month",
      "benefits": ["Medical", "Baggage Loss", "Trip Cancellation"],
      "cashback": 5,
      "icon": "https://example.com/logos/travelguard.png",
      "url": "https://www.travelguard.ca"
    }
  ]
  