export const plans = [
  {
    "id": 1,
    "provider": "BlueCross",
    "type": "Health",
    "price": 150,
    "coverage": "Basic health coverage including prescriptions and emergency visits",
    "region": "ON",
    "rating": 4.5,
    "term": "1 year",
    "benefits": ["Prescription Coverage", "Emergency Services"],
    "giftcard": "upto 10",
    "icon": "https://www.pac.bluecross.ca/images/pbc_logo.svg",
    "url": "https://www.bluecross.ca"
  },
  {
    "id": 2,
    "provider": "Sun Life",
    "type": "Life",
    "price": 200,
    "coverage": "Life insurance with accidental death coverage",
    "region": "BC",
    "rating": 4.7,
    "term": "5 years",
    "benefits": ["Accidental Death", "Terminal Illness"],
    "giftcard": "upto 15",
    "icon": "https://www.sunlife.ca/content/dam/sunlife/global/logos/sun-life/current/sun-life-weblogo-127x31.svg",
    "url": "https://www.sunlife.ca"
  },
  {
    "id": 3,
    "provider": "ICBC",
    "type": "Auto",
    "price": 120,
    "coverage": "Basic Autoplan mandatory coverage: third-party liability, accident benefits, underinsured motorist protection, vehicle damage",
    "region": "BC",
    "rating": 4.3,
    "term": "1 year",
    "benefits": ["Third-Party Liability", "Accident Benefits", "Vehicle Damage"],
    "giftcard": "upto 0",
    "icon": "https://images.ctfassets.net/nnc41duedoho/VsfCm5S9VzUFeu2jxlPRi/3dbe8d24b4f6bbbe51d8374be24d6678/icbc-logo-orange.svg?w=128&q=75",
    "url": "https://www.icbc.com"
  },
  {
    "id": 4,
    "provider": "BCAA",
    "type": "Auto",
    "price": 90,
    "coverage": "Optional car insurance supplementing Basic Autoplan",
    "region": "BC",
    "rating": 4.4,
    "term": "1 year",
    "benefits": ["Theft Protection", "Collision Damage", "Family Discounts"],
    "giftcard": "upto 5",
    "icon": "https://www.bcaa.com/-/media/bcaa/images/logos/bcaa_caa_primary_hex_rev.svg?iar=0&hash=63BA45A9DC57859ACEE50CD06C7F6884",
    "url": "https://www.bcaa.com/insurance/car"
  },
  {
    "id": 5,
    "provider": "Manulife",
    "type": "Health",
    "price": 180,
    "coverage": "Extended health coverage including dental, vision, and prescriptions",
    "region": "AB",
    "rating": 4.6,
    "term": "1 year",
    "benefits": ["Dental", "Vision", "Prescription Coverage", "Emergency Services"],
    "giftcard": "upto 15",
    "icon": "https://www.manulife.ca/content/dam/consumer-portal/logo/en/manulife-home-100.svg",
    "url": "https://www.manulife.ca/en/insurance/health.html"
  },
  {
    "id": 6,
    "provider": "Intact Insurance",
    "type": "Home",
    "price": 95,
    "coverage": "Home insurance including fire, theft, and natural disasters",
    "region": "ON",
    "rating": 4.4,
    "term": "1 year",
    "benefits": ["Fire Protection", "Theft Coverage", "Natural Disasters"],
    "giftcard": "upto 10",
    "icon": "https://www.intact.ca/static/images/intactinsurance.svg",
    "url": "https://www.intact.ca"
  },
  {
    "id": 7,
    "provider": "RBC Insurance",
    "type": "Auto",
    "price": 130,
    "coverage": "Third-party liability and collision coverage",
    "region": "MB",
    "rating": 4.2,
    "term": "1 year",
    "benefits": ["Liability", "Collision", "Accident Coverage"],
    "giftcard": "upto 10",
    "icon": "https://www.rbcinsurance.com/en-ca/wp-content/themes/rbc/img/logos/rbc-logo-shield.svg",
    "url": "https://www.rbcinsurance.com"
  },
  {
    "id": 8,
    "provider": "Westland Insurance",
    "type": "Auto",
    "price": 110,
    "coverage": "Optional coverage for BC cars, includes Family Autocover package",
    "region": "BC",
    "rating": 4.3,
    "term": "1 year",
    "benefits": ["Collision", "Theft", "Family Package"],
    "giftcard": "upto 8",
    "icon": "https://www.westlandinsurance.ca/wp-content/uploads/2021/08/logo-full-dark.svg",
    "url": "https://www.westlandinsurance.ca/auto/car-insurance/bc"
  },
  {
    "id": 9,
    "provider": "Co-operators",
    "type": "Home",
    "price": 100,
    "coverage": "Comprehensive home coverage with natural disaster protection",
    "region": "AB",
    "rating": 4.5,
    "term": "1 year",
    "benefits": ["Fire", "Theft", "Natural Disasters"],
    "giftcard": "upto 10",
    "icon": "https://www.cooperators.ca/-/media/cooperators/assets/home/home-page-logo/co-operators-logo-svg.svg",
    "url": "https://www.cooperators.ca"
  },
  {
    "id": 10,
    "provider": "Empire Life",
    "type": "Life",
    "price": 195,
    "coverage": "Term life insurance with optional accidental death benefit",
    "region": "NS",
    "rating": 4.4,
    "term": "5 years",
    "benefits": ["Accidental Death", "Terminal Illness"],
    "giftcard": "upto 10",
    "icon": "https://www.empire.ca/sites/default/files/logos/logo-en.png",
    "url": "https://www.empire.ca"
  },
  {
    "id": 11,
    "provider": "Manulife",
    "type": "Travel",
    "price": 60,
    "coverage": "Travel insurance covering medical and trip interruption",
    "region": "QC",
    "rating": 4.5,
    "term": "1 month",
    "benefits": ["Medical", "Trip Cancellation", "Baggage Loss"],
    "giftcard": "upto 5",
    "icon": "https://www.manulife.ca/content/dam/consumer-portal/logo/en/manulife-home-100.svg",
    "url": "https://www.manulife.ca/en/insurance/travel.html"
  },
  {
    "id": 12,
    "provider": "Intact Insurance",
    "type": "Home",
    "price": 90,
    "coverage": "Home insurance covering fire, theft, and water damage",
    "region": "MB",
    "rating": 4.3,
    "term": "1 year",
    "benefits": ["Fire", "Theft", "Water Damage"],
    "giftcard": "upto 8",
    "icon": "https://www.intact.ca/static/images/intactinsurance.svg",
    "url": "https://www.intact.ca"
  },
  {
    "id": 13,
    "provider": "Sun Life",
    "type": "Life",
    "price": 205,
    "coverage": "Life insurance with optional critical illness rider",
    "region": "ON",
    "rating": 4.6,
    "term": "5 years",
    "benefits": ["Critical Illness", "Accidental Death"],
    "giftcard": "upto 10",
    "icon": "https://www.sunlife.ca/content/dam/sunlife/global/logos/sun-life/current/sun-life-weblogo-127x31.svg",
    "url": "https://www.sunlife.ca"
  },
  {
    "id": 14,
    "provider": "Westland Insurance",
    "type": "Auto",
    "price": 100,
    "coverage": "Optional BC car insurance with Family Autocover",
    "region": "BC",
    "rating": 4.3,
    "term": "1 year",
    "benefits": ["Collision", "Theft", "Family Package"],
    "giftcard": "upto 7",
    "icon": "https://www.westlandinsurance.ca/wp-content/uploads/2021/08/logo-full-dark.svg",
    "url": "https://www.westlandinsurance.ca/auto/car-insurance/bc"
  },
  {
    "id": 15,
    "provider": "Co-operators",
    "type": "Home",
    "price": 105,
    "coverage": "Comprehensive home coverage with natural disaster protection",
    "region": "NB",
    "rating": 4.4,
    "term": "1 year",
    "benefits": ["Fire", "Theft", "Natural Disasters"],
    "giftcard": "upto 9",
    "icon": "https://www.cooperators.ca/-/media/cooperators/assets/home/home-page-logo/co-operators-logo-svg.svg",
    "url": "https://www.cooperators.ca"
  },
  {
    "id": 16,
    "provider": "Empire Life",
    "type": "Life",
    "price": 215,
    "coverage": "Life insurance with optional disability and terminal illness",
    "region": "AB",
    "rating": 4.6,
    "term": "10 years",
    "benefits": ["Disability Coverage", "Terminal Illness"],
    "giftcard": "upto 12",
    "icon": "https://www.empire.ca/sites/default/files/logos/logo-en.png",
    "url": "https://www.empire.ca"
  },
  {
    "id": 17,
    "provider": "BlueCross",
    "type": "Health",
    "price": 175,
    "coverage": "Comprehensive health coverage including dental, vision, and prescriptions",
    "region": "AB",
    "rating": 4.5,
    "term": "1 year",
    "benefits": ["Dental", "Vision", "Prescription Coverage"],
    "giftcard": "upto 15",
    "icon": "https://www.pac.bluecross.ca/images/pbc_logo.svg",
    "url": "https://www.bluecross.ca"
  },
  {
    "id": 18,
    "provider": "Aviva",
    "type": "Home",
    "price": 115,
    "coverage": "Home insurance covering theft, fire, and liability",
    "region": "ON",
    "rating": 4.4,
    "term": "1 year",
    "benefits": ["Fire", "Theft", "Liability"],
    "giftcard": "upto 8",
    "icon": "https://imgs.search.brave.com/xvthvu8dcBtgvyXq9ev4PDt4J9k0FWNih6FCcrm6hp8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly8xMDAw/bG9nb3MubmV0L3dw/LWNvbnRlbnQvdXBs/aW5rcy8yMDIxLzA0/L0F2aXZhLWxvZ28t/NTAweDI4MS5wbmc",
    "url": "https://www.aviva.ca"
  },
  {
    "id": 19,
    "provider": "Canada Life",
    "type": "Life",
    "price": 220,
    "coverage": "Life insurance with critical illness and disability coverage",
    "region": "QC",
    "rating": 4.6,
    "term": "10 years",
    "benefits": ["Critical Illness", "Disability"],
    "giftcard": "upto 15",
    "icon": "https://www.canadalife.com/content/dam/canadalife/logos/canada-life-e-tm.323032332d30382d33303a31303a3134.svg",
    "url": "https://www.canadalife.com"
  },
  {
    "id": 20,
    "provider": "TD Insurance",
    "type": "Auto",
    "price": 135,
    "coverage": "Auto insurance with liability, theft, and collision coverage",
    "region": "ON",
    "rating": 4.3,
    "term": "1 year",
    "benefits": ["Liability", "Theft", "Collision"],
    "giftcard": "upto 9",
    "icon": "https://www.tdinsurance.com/content/dam/tdinsurance/images/header-and-footer/tdi-desktop-logo-en.png",
    "url": "https://www.tdinsurance.com"
  },
  {
    "id": 21,
    "provider": "Allianz",
    "type": "Travel",
    "price": 75,
    "coverage": "Travel insurance including medical emergencies and baggage loss",
    "region": "ON",
    "rating": 4.4,
    "term": "1 month",
    "benefits": ["Medical Emergencies", "Baggage Loss", "Trip Cancellation"],
    "giftcard": "upto 5",
    "icon": "https://imgs.search.brave.com/BpftFdOcsYQz8pDfZ2G59tC-MunruyagXbLoouES8GE/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMuc2Vla2xvZ28u/Y29tL2xvZ28tcG5n/LzAvMi9hbGxpYW56/LWJ1bGdhcmlhLWxv/Z28tcG5nX3NlZWts/b2dvLTY4NjkucG5n",
    "url": "https://www.allianz-assistance.ca"
  },
  {
    "id": 22,
    "provider": "TuGo",
    "type": "Travel",
    "price": 55,
    "coverage": "Travel insurance covering trip cancellation and medical emergencies",
    "region": "BC",
    "rating": 4.3,
    "term": "1 month",
    "benefits": ["Medical Emergencies", "Trip Cancellation"],
    "giftcard": "upto 5",
    "icon": "https://www.tugo.com/images/tugo_logo_en.svg",
    "url": "https://www.tugo.com"
  },
  {
    "id": 23,
    "provider": "Green Shield",
    "type": "Health",
    "price": 165,
    "coverage": "Health plan including vision, dental, and prescriptions",
    "region": "NB",
    "rating": 4.4,
    "term": "1 year",
    "benefits": ["Vision", "Dental", "Prescription Coverage"],
    "giftcard": "upto 12",
    "icon": "https://imgs.search.brave.com/g9RSPmYknbh3cGbbfuc4JUzubWulZX-GURwIDvb2OwY/rs:fit:0:180:1:0/g:ce/aHR0cHM6Ly9zYmlz/LmNhL3dwLWNvbnRl/bnQvdXBsb2Fkcy8y/MDIzLzAzL0dTLnN2/Zw",
    "url": "https://www.greenshield.ca"
  },
  {
    "id": 24,
    "provider": "Definity",
    "type": "Home",
    "price": 110,
    "coverage": "Home insurance with protection against fire, theft, and storms",
    "region": "NS",
    "rating": 4.3,
    "term": "1 year",
    "benefits": ["Fire", "Theft", "Storm Damage"],
    "giftcard": "upto 9",
    "icon": "https://s28.q4cdn.com/441925426/files/design/header-logo.png",
    "url": "https://www.definityfinancial.com"
  },
  {
    "id": 25,
    "provider": "Sun Life",
    "type": "Life",
    "price": 210,
    "coverage": "Life insurance with critical illness rider",
    "region": "PE",
    "rating": 4.6,
    "term": "15 years",
    "benefits": ["Critical Illness", "Accidental Death"],
    "giftcard": "upto 14",
    "icon": "https://www.sunlife.ca/content/dam/sunlife/global/logos/sun-life/current/sun-life-weblogo-127x31.svg",
    "url": "https://www.sunlife.ca"
  },
  {
    "id": 26,
    "provider": "ICBC",
    "type": "Auto",
    "price": 125,
    "coverage": "Basic Autoplan with optional collision and liability add-ons",
    "region": "BC",
    "rating": 4.3,
    "term": "1 year",
    "benefits": ["Third-Party Liability", "Collision", "Accident Benefits"],
    "giftcard": "upto 5",
    "icon": "https://images.ctfassets.net/nnc41duedoho/VsfCm5S9VzUFeu2jxlPRi/3dbe8d24b4f6bbbe51d8374be24d6678/icbc-logo-orange.svg?w=128&q=75",
    "url": "https://www.icbc.com"
  },
  {
    "id": 27,
    "provider": "BCAA",
    "type": "Auto",
    "price": 100,
    "coverage": "Optional auto insurance for BC drivers covering theft and collision",
    "region": "BC",
    "rating": 4.4,
    "term": "1 year",
    "benefits": ["Theft", "Collision", "Family Discounts"],
    "giftcard": "upto 5",
    "icon": "https://www.bcaa.com/-/media/bcaa/images/logos/bcaa_caa_primary_hex_rev.svg?iar=0&hash=63BA45A9DC57859ACEE50CD06C7F6884",
    "url": "https://www.bcaa.com/insurance/car"
  },
  {
    "id": 28,
    "provider": "RBC Insurance",
    "type": "Auto",
    "price": 140,
    "coverage": "Auto coverage with liability, accident, and roadside assistance",
    "region": "ON",
    "rating": 4.3,
    "term": "1 year",
    "benefits": ["Liability", "Accident Benefits", "Roadside Assistance"],
    "giftcard": "upto 10",
    "icon": "https://www.rbcinsurance.com/en-ca/wp-content/themes/rbc/img/logos/rbc-logo-shield.svg",
    "url": "https://www.rbcinsurance.com"
  },
  {
    "id": 29,
    "provider": "Westland Insurance",
    "type": "Auto",
    "price": 120,
    "coverage": "Comprehensive auto insurance with theft, collision, and family package",
    "region": "AB",
    "rating": 4.4,
    "term": "1 year",
    "benefits": ["Collision", "Theft", "Family Package"],
    "giftcard": "upto 9",
    "icon": "https://www.westlandinsurance.ca/wp-content/uploads/2021/08/logo-full-dark.svg",
    "url": "https://www.westlandinsurance.ca/auto/car-insurance/bc"
  },
  {
    "id": 30,
    "provider": "Manulife",
    "type": "Health",
    "price": 190,
    "coverage": "Extended health coverage including dental, vision, and prescriptions",
    "region": "NB",
    "rating": 4.6,
    "term": "1 year",
    "benefits": ["Dental", "Vision", "Prescription Coverage"],
    "giftcard": "upto 15",
    "icon": "https://www.manulife.ca/content/dam/consumer-portal/logo/en/manulife-home-100.svg",
    "url": "https://www.manulife.ca"
  },
  {
    "id": 31,
    "provider": "Empire Life",
    "type": "Life",
    "price": 225,
    "coverage": "Life insurance with accidental death and terminal illness rider",
    "region": "ON",
    "rating": 4.5,
    "term": "10 years",
    "benefits": ["Accidental Death", "Terminal Illness"],
    "giftcard": "upto 12",
    "icon": "https://www.empire.ca/sites/default/files/logos/logo-en.png",
    "url": "https://www.empire.ca"
  },
  {
    "id": 32,
    "provider": "Aviva",
    "type": "Home",
    "price": 120,
    "coverage": "Home insurance with fire, theft, and liability protection",
    "region": "QC",
    "rating": 4.4,
    "term": "1 year",
    "benefits": ["Fire", "Theft", "Liability"],
    "giftcard": "upto 9",
    "icon": "https://imgs.search.brave.com/xvthvu8dcBtgvyXq9ev4PDt4J9k0FWNih6FCcrm6hp8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly8xMDAw/bG9nb3MubmV0L3dw/LWNvbnRlbnQvdXBs/aW5rcy8yMDIxLzA0/L0F2aXZhLWxvZ28t/NTAweDI4MS5wbmc",
    "url": "https://www.aviva.ca"
  },
  {
    "id": 33,
    "provider": "Canada Life",
    "type": "Life",
    "price": 230,
    "coverage": "Life insurance plan with critical illness and accidental death",
    "region": "ON",
    "rating": 4.6,
    "term": "15 years",
    "benefits": ["Critical Illness", "Accidental Death"],
    "giftcard": "upto 15",
    "icon": "https://www.canadalife.com/content/dam/canadalife/logos/canada-life-e-tm.323032332d30382d33303a31303a3134.svg",
    "url": "https://www.canadalife.com"
  },
  {
    "id": 34,
    "provider": "TD Insurance",
    "type": "Auto",
    "price": 145,
    "coverage": "Auto plan with liability, theft, and collision",
    "region": "QC",
    "rating": 4.3,
    "term": "1 year",
    "benefits": ["Liability", "Theft", "Collision"],
    "giftcard": "upto 10",
    "icon": "https://www.tdinsurance.com/content/dam/tdinsurance/images/header-and-footer/tdi-desktop-logo-en.png",
    "url": "https://www.tdinsurance.com"
  },
  {
    "id": 35,
    "provider": "BlueCross",
    "type": "Health",
    "price": 160,
    "coverage": "Health plan with prescriptions, vision, and dental",
    "region": "NS",
    "rating": 4.5,
    "term": "1 year",
    "benefits": ["Vision", "Dental", "Prescription Coverage"],
    "giftcard": "upto 12",
    "icon": "https://www.pac.bluecross.ca/images/pbc_logo.svg",
    "url": "https://www.bluecross.ca"
  },
  {
    "id": 36,
    "provider": "Intact Insurance",
    "type": "Home",
    "price": 105,
    "coverage": "Home insurance covering fire, theft, and water damage",
    "region": "PE",
    "rating": 4.3,
    "term": "1 year",
    "benefits": ["Fire", "Theft", "Water Damage"],
    "giftcard": "upto 10",
    "icon": "https://www.intact.ca/static/images/intactinsurance.svg",
    "url": "https://www.intact.ca"
  },
  {
    "id": 37,
    "provider": "Allianz",
    "type": "Travel",
    "price": 85,
    "coverage": "Travel insurance including trip interruption and medical emergencies",
    "region": "NB",
    "rating": 4.5,
    "term": "1 month",
    "benefits": ["Medical Emergencies", "Trip Interruption", "Baggage Loss"],
    "giftcard": "upto 5",
    "icon": "https://imgs.search.brave.com/BpftFdOcsYQz8pDfZ2G59tC-MunruyagXbLoouES8GE/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMuc2Vla2xvZ28u/Y29tL2xvZ28tcG5n/LzAvMi9hbGxpYW56/LWJ1bGdhcmlhLWxv/Z28tcG5nX3NlZWts/b2dvLTY4NjkucG5n",
    "url": "https://www.allianz-assistance.ca"
  },
  {
    "id": 38,
    "provider": "TuGo",
    "type": "Travel",
    "price": 65,
    "coverage": "Travel plan with baggage loss and emergency medical coverage",
    "region": "AB",
    "rating": 4.4,
    "term": "1 month",
    "benefits": ["Medical Emergencies", "Baggage Loss"],
    "giftcard": "upto 5",
    "icon": "https://www.tugo.com/images/tugo_logo_en.svg",
    "url": "https://www.tugo.com"
  },
  {
    "id": 39,
    "provider": "Sun Life",
    "type": "Life",
    "price": 240,
    "coverage": "Life insurance with critical illness and accidental death",
    "region": "MB",
    "rating": 4.7,
    "term": "20 years",
    "benefits": ["Critical Illness", "Accidental Death"],
    "giftcard": "upto 15",
    "icon": "https://www.sunlife.ca/content/dam/sunlife/global/logos/sun-life/current/sun-life-weblogo-127x31.svg",
    "url": "https://www.sunlife.ca"
  },
  {
    "id": 40,
    "provider": "Green Shield",
    "type": "Health",
    "price": 170,
    "coverage": "Health plan with prescriptions, dental, and emergency services",
    "region": "AB",
    "rating": 4.5,
    "term": "1 year",
    "benefits": ["Dental", "Prescription Coverage", "Emergency Services"],
    "giftcard": "upto 12",
    "icon": "https://imgs.search.brave.com/g9RSPmYknbh3cGbbfuc4JUzubWulZX-GURwIDvb2OwY/rs:fit:0:180:1:0/g:ce/aHR0cHM6Ly9zYmlz/LmNhL3dwLWNvbnRl/bnQvdXBsb2Fkcy8y/MDIzLzAzL0dTLnN2/Zw",
    "url": "https://www.greenshield.ca"
  },
  {
    "id": 41,
    "provider": "Empire Life",
    "type": "Life",
    "price": 250,
    "coverage": "Life insurance with terminal illness and disability rider",
    "region": "PE",
    "rating": 4.6,
    "term": "25 years",
    "benefits": ["Terminal Illness", "Disability Coverage"],
    "giftcard": "upto 12",
    "icon": "https://www.empire.ca/sites/default/files/logos/logo-en.png",
    "url": "https://www.empire.ca"
  },
  {
    "id": 42,
    "provider": "Co-operators",
    "type": "Home",
    "price": 115,
    "coverage": "Comprehensive home coverage with flood and sewer backup protection",
    "region": "ON",
    "rating": 4.4,
    "term": "1 year",
    "benefits": ["Flooding", "Sewer Backup", "Fire"],
    "giftcard": "upto 10",
    "icon": "https://www.cooperators.ca/-/media/cooperators/assets/home/home-page-logo/co-operators-logo-svg.svg",
    "url": "https://www.cooperators.ca"
  },
  {
    "id": 43,
    "provider": "Definity",
    "type": "Home",
    "price": 112,
    "coverage": "Home coverage with theft, fire, and natural disaster protection",
    "region": "NB",
    "rating": 4.3,
    "term": "1 year",
    "benefits": ["Fire", "Theft", "Natural Disasters"],
    "giftcard": "upto 9",
    "icon": "https://s28.q4cdn.com/441925426/files/design/header-logo.png",
    "url": "https://www.definityfinancial.com"
  },
  {
    "id": 44,
    "provider": "Intact Insurance",
    "type": "Home",
    "price": 125,
    "coverage": "Home insurance covering theft, liability, and storm damage",
    "region": "ON",
    "rating": 4.4,
    "term": "1 year",
    "benefits": ["Theft", "Liability", "Storm Damage"],
    "giftcard": "upto 10",
    "icon": "https://www.intact.ca/static/images/intactinsurance.svg",
    "url": "https://www.intact.ca"
  },
  {
    "id": 45,
    "provider": "BlueCross",
    "type": "Health",
    "price": 180,
    "coverage": "Comprehensive health coverage with dental and physiotherapy",
    "region": "QC",
    "rating": 4.6,
    "term": "1 year",
    "benefits": ["Dental", "Physiotherapy", "Prescription Coverage"],
    "giftcard": "upto 14",
    "icon": "https://www.pac.bluecross.ca/images/pbc_logo.svg",
    "url": "https://www.bluecross.ca"
  },
  {
    "id": 46,
    "provider": "TD Insurance",
    "type": "Auto",
    "price": 150,
    "coverage": "Auto insurance with liability, collision, and accident benefits",
    "region": "NB",
    "rating": 4.3,
    "term": "1 year",
    "benefits": ["Liability", "Collision", "Accident Benefits"],
    "giftcard": "upto 10",
    "icon": "https://www.tdinsurance.com/content/dam/tdinsurance/images/header-and-footer/tdi-desktop-logo-en.png",
    "url": "https://www.tdinsurance.com"
  },
  {
    "id": 47,
    "provider": "Sun Life",
    "type": "Life",
    "price": 225,
    "coverage": "Life plan with critical illness and disability rider",
    "region": "AB",
    "rating": 4.7,
    "term": "20 years",
    "benefits": ["Critical Illness", "Disability Coverage"],
    "giftcard": "upto 15",
    "icon": "https://www.sunlife.ca/content/dam/sunlife/global/logos/sun-life/current/sun-life-weblogo-127x31.svg",
    "url": "https://www.sunlife.ca"
  },
  {
    "id": 48,
    "provider": "RBC Insurance",
    "type": "Auto",
    "price": 138,
    "coverage": "Auto plan including liability, accident benefits, and theft",
    "region": "AB",
    "rating": 4.4,
    "term": "1 year",
    "benefits": ["Liability", "Accident Benefits", "Theft"],
    "giftcard": "upto 9",
    "icon": "https://www.rbcinsurance.com/en-ca/wp-content/themes/rbc/img/logos/rbc-logo-shield.svg",
    "url": "https://www.rbcinsurance.com"
  },
  {
    "id": 49,
    "provider": "Aviva",
    "type": "Home",
    "price": 118,
    "coverage": "Home insurance covering fire, theft, and earthquake protection",
    "region": "BC",
    "rating": 4.3,
    "term": "1 year",
    "benefits": ["Fire", "Theft", "Earthquake"],
    "giftcard": "upto 8",
    "icon": "https://imgs.search.brave.com/xvthvu8dcBtgvyXq9ev4PDt4J9k0FWNih6FCcrm6hp8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly8xMDAw/bG9nb3MubmV0L3dw/LWNvbnRlbnQvdXBs/aW5rcy8yMDIxLzA0/L0F2aXZhLWxvZ28t/NTAweDI4MS5wbmc",
    "url": "https://www.aviva.ca"
  },
  {
    "id": 50,
    "provider": "Canada Life",
    "type": "Life",
    "price": 235,
    "coverage": "Life plan with critical illness, disability, and accidental death",
    "region": "BC",
    "rating": 4.6,
    "term": "25 years",
    "benefits": ["Critical Illness", "Disability", "Accidental Death"],
    "giftcard": "upto 15",
    "icon": "https://www.canadalife.com/content/dam/canadalife/logos/canada-life-e-tm.323032332d30382d33303a31303a3134.svg",
    "url": "https://www.canadalife.com"
  },
  {
    "id": 51,
    "provider": "Manulife",
    "type": "Health",
    "price": 185,
    "coverage": "Extended health coverage including dental, prescriptions, and physiotherapy",
    "region": "QC",
    "rating": 4.6,
    "term": "1 year",
    "benefits": ["Dental", "Physiotherapy", "Prescription Coverage"],
    "giftcard": "upto 15",
    "icon": "https://www.manulife.ca/content/dam/consumer-portal/logo/en/manulife-home-100.svg",
    "url": "https://www.manulife.ca"
  },
  {
    "id": 52,
    "provider": "BlueCross",
    "type": "Health",
    "price": 175,
    "coverage": "Basic health plan with vision and prescription coverage",
    "region": "NB",
    "rating": 4.5,
    "term": "1 year",
    "benefits": ["Vision", "Prescription Coverage", "Emergency Services"],
    "giftcard": "upto 12",
    "icon": "https://www.pac.bluecross.ca/images/pbc_logo.svg",
    "url": "https://www.bluecross.ca"
  },
  {
    "id": 53,
    "provider": "Aviva",
    "type": "Home",
    "price": 122,
    "coverage": "Comprehensive home insurance with theft, liability, and natural disasters",
    "region": "ON",
    "rating": 4.4,
    "term": "1 year",
    "benefits": ["Theft", "Liability", "Natural Disasters"],
    "giftcard": "upto 9",
    "icon": "https://imgs.search.brave.com/xvthvu8dcBtgvyXq9ev4PDt4J9k0FWNih6FCcrm6hp8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly8xMDAw/bG9nb3MubmV0L3dw/LWNvbnRlbnQvdXBs/aW5rcy8yMDIxLzA0/L0F2aXZhLWxvZ28t/NTAweDI4MS5wbmc",
    "url": "https://www.aviva.ca"
  },
  {
    "id": 54,
    "provider": "Allianz",
    "type": "Travel",
    "price": 75,
    "coverage": "Travel insurance for international trips with emergency medical support",
    "region": "ON",
    "rating": 4.4,
    "term": "1 month",
    "benefits": ["Medical Emergencies", "Trip Interruption"],
    "giftcard": "upto 5",
    "icon": "https://imgs.search.brave.com/BpftFdOcsYQz8pDfZ2G59tC-MunruyagXbLoouES8GE/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMuc2Vla2xvZ28u/Y29tL2xvZ28tcG5n/LzAvMi9hbGxpYW56/LWJ1bGdhcmlhLWxv/Z28tcG5nX3NlZWts/b2dvLTY4NjkucG5n",
    "url": "https://www.allianz-assistance.ca"
  },
  {
    "id": 55,
    "provider": "Sun Life",
    "type": "Life",
    "price": 210,
    "coverage": "Life insurance with critical illness and accidental death benefits",
    "region": "QC",
    "rating": 4.7,
    "term": "20 years",
    "benefits": ["Critical Illness", "Accidental Death"],
    "giftcard": "upto 14",
    "icon": "https://www.sunlife.ca/content/dam/sunlife/global/logos/sun-life/current/sun-life-weblogo-127x31.svg",
    "url": "https://www.sunlife.ca"
  },
  {
    "id": 56,
    "provider": "Empire Life",
    "type": "Life",
    "price": 220,
    "coverage": "Term life insurance with disability and terminal illness coverage",
    "region": "NS",
    "rating": 4.5,
    "term": "15 years",
    "benefits": ["Terminal Illness", "Disability"],
    "giftcard": "upto 12",
    "icon": "https://www.empire.ca/sites/default/files/logos/logo-en.png",
    "url": "https://www.empire.ca"
  },
  {
    "id": 57,
    "provider": "TD Insurance",
    "type": "Auto",
    "price": 135,
    "coverage": "Auto plan with liability, collision, and roadside assistance",
    "region": "ON",
    "rating": 4.3,
    "term": "1 year",
    "benefits": ["Liability", "Collision", "Roadside Assistance"],
    "giftcard": "upto 9",
    "icon": "https://www.tdinsurance.com/content/dam/tdinsurance/images/header-and-footer/tdi-desktop-logo-en.png",
    "url": "https://www.tdinsurance.com"
  },
  {
    "id": 58,
    "provider": "Green Shield",
    "type": "Health",
    "price": 165,
    "coverage": "Health insurance covering dental, prescriptions, and wellness services",
    "region": "AB",
    "rating": 4.4,
    "term": "1 year",
    "benefits": ["Dental", "Prescription Coverage", "Wellness"],
    "giftcard": "upto 11",
    "icon": "https://imgs.search.brave.com/g9RSPmYknbh3cGbbfuc4JUzubWulZX-GURwIDvb2OwY/rs:fit:0:180:1:0/g:ce/aHR0cHM6Ly9zYmlz/LmNhL3dwLWNvbnRl/bnQvdXBsb2Fkcy8y/MDIzLzAzL0dTLnN2/Zw",
    "url": "https://www.greenshield.ca"
  },
  {
    "id": 59,
    "provider": "Westland Insurance",
    "type": "Auto",
    "price": 128,
    "coverage": "Optional auto insurance including theft and family coverage",
    "region": "BC",
    "rating": 4.3,
    "term": "1 year",
    "benefits": ["Theft", "Collision", "Family Coverage"],
    "giftcard": "upto 9",
    "icon": "https://www.westlandinsurance.ca/wp-content/uploads/2021/08/logo-full-dark.svg",
    "url": "https://www.westlandinsurance.ca"
  },
  {
    "id": 60,
    "provider": "Intact Insurance",
    "type": "Home",
    "price": 110,
    "coverage": "Home plan with water damage, theft, and fire coverage",
    "region": "NB",
    "rating": 4.4,
    "term": "1 year",
    "benefits": ["Water Damage", "Theft", "Fire"],
    "giftcard": "upto 8",
    "icon": "https://www.intact.ca/static/images/intactinsurance.svg",
    "url": "https://www.intact.ca"
  },
  {
    "id": 61,
    "provider": "Co-operators",
    "type": "Home",
    "price": 108,
    "coverage": "Comprehensive home insurance with liability and theft protection",
    "region": "QC",
    "rating": 4.5,
    "term": "1 year",
    "benefits": ["Liability", "Theft", "Fire"],
    "giftcard": "upto 9",
    "icon": "https://www.cooperators.ca/-/media/cooperators/assets/home/home-page-logo/co-operators-logo-svg.svg",
    "url": "https://www.cooperators.ca"
  },
  {
    "id": 62,
    "provider": "Allianz",
    "type": "Travel",
    "price": 70,
    "coverage": "Travel insurance covering baggage loss and trip cancellation",
    "region": "BC",
    "rating": 4.3,
    "term": "1 month",
    "benefits": ["Baggage Loss", "Trip Cancellation", "Medical Emergencies"],
    "giftcard": "upto 5",
    "icon": "https://imgs.search.brave.com/BpftFdOcsYQz8pDfZ2G59tC-MunruyagXbLoouES8GE/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMuc2Vla2xvZ28u/Y29tL2xvZ28tcG5n/LzAvMi9hbGxpYW56/LWJ1bGdhcmlhLWxv/Z28tcG5nX3NlZWts/b2dvLTY4NjkucG5n",
    "url": "https://www.allianz-assistance.ca"
  },
  {
    "id": 63,
    "provider": "Definity",
    "type": "Home",
    "price": 118,
    "coverage": "Home insurance with earthquake, theft, and natural disaster coverage",
    "region": "AB",
    "rating": 4.3,
    "term": "1 year",
    "benefits": ["Earthquake", "Theft", "Natural Disasters"],
    "giftcard": "upto 8",
    "icon": "https://s28.q4cdn.com/441925426/files/design/header-logo.png",
    "url": "https://www.definityfinancial.com"
  },
  {
    "id": 64,
    "provider": "TuGo",
    "type": "Travel",
    "price": 60,
    "coverage": "Travel insurance with medical, trip cancellation, and baggage loss",
    "region": "PE",
    "rating": 4.4,
    "term": "1 month",
    "benefits": ["Medical Emergencies", "Trip Cancellation", "Baggage Loss"],
    "giftcard": "upto 5",
    "icon": "https://www.tugo.com/images/tugo_logo_en.svg",
    "url": "https://www.tugo.com"
  },
  {
    "id": 65,
    "provider": "Canada Life",
    "type": "Life",
    "price": 245,
    "coverage": "Life plan with critical illness, disability, and accidental death coverage",
    "region": "AB",
    "rating": 4.7,
    "term": "25 years",
    "benefits": ["Critical Illness", "Disability", "Accidental Death"],
    "giftcard": "upto 15",
    "icon": "https://www.canadalife.com/content/dam/canadalife/logos/canada-life-e-tm.323032332d30382d33303a31303a3134.svg",
    "url": "https://www.canadalife.com"
  },
  {
    "id": 66,
    "provider": "BlueCross",
    "type": "Health",
    "price": 155,
    "coverage": "Basic health coverage including prescriptions and emergency visits",
    "region": "ON",
    "rating": 4.5,
    "term": "1 year",
    "benefits": ["Prescription Coverage", "Emergency Services"],
    "giftcard": "upto 10",
    "icon": "https://www.pac.bluecross.ca/images/pbc_logo.svg",
    "url": "https://www.bluecross.ca"
  },
  {
    "id": 67,
    "provider": "Intact Insurance",
    "type": "Home",
    "price": 120,
    "coverage": "Home plan with theft, liability, and flood protection",
    "region": "ON",
    "rating": 4.4,
    "term": "1 year",
    "benefits": ["Theft", "Liability", "Flood"],
    "giftcard": "upto 10",
    "icon": "https://www.intact.ca/static/images/intactinsurance.svg",
    "url": "https://www.intact.ca"
  },
  {
    "id": 68,
    "provider": "Sun Life",
    "type": "Life",
    "price": 200,
    "coverage": "Life plan with terminal illness and accidental death protection",
    "region": "PE",
    "rating": 4.6,
    "term": "15 years",
    "benefits": ["Terminal Illness", "Accidental Death"],
    "giftcard": "upto 12",
    "icon": "https://www.sunlife.ca/content/dam/sunlife/global/logos/sun-life/current/sun-life-weblogo-127x31.svg",
    "url": "https://www.sunlife.ca"
  },
  {
    "id": 69,
    "provider": "Green Shield",
    "type": "Health",
    "price": 180,
    "coverage": "Comprehensive health insurance with dental and prescriptions",
    "region": "MB",
    "rating": 4.5,
    "term": "1 year",
    "benefits": ["Dental", "Prescription Coverage"],
    "giftcard": "upto 13",
    "icon": "https://imgs.search.brave.com/g9RSPmYknbh3cGbbfuc4JUzubWulZX-GURwIDvb2OwY/rs:fit:0:180:1:0/g:ce/aHR0cHM6Ly9zYmlz/LmNhL3dwLWNvbnRl/bnQvdXBsb2Fkcy8y/MDIzLzAzL0dTLnN2/Zw",
    "url": "https://www.greenshield.ca"
  },
  {
    "id": 70,
    "provider": "Westland Insurance",
    "type": "Auto",
    "price": 115,
    "coverage": "Auto coverage with liability, theft, and accident protection",
    "region": "NB",
    "rating": 4.3,
    "term": "1 year",
    "benefits": ["Liability", "Theft", "Accident Coverage"],
    "giftcard": "upto 9",
    "icon": "https://www.westlandinsurance.ca/wp-content/uploads/2021/08/logo-full-dark.svg",
    "url": "https://www.westlandinsurance.ca"
  },
  {
    "id": 71,
    "provider": "Empire Life",
    "type": "Life",
    "price": 215,
    "coverage": "Life insurance with disability and terminal illness rider",
    "region": "NB",
    "rating": 4.6,
    "term": "20 years",
    "benefits": ["Disability", "Terminal Illness"],
    "giftcard": "upto 12",
    "icon": "https://www.empire.ca/sites/default/files/logos/logo-en.png",
    "url": "https://www.empire.ca"
  },
  {
    "id": 72,
    "provider": "TD Insurance",
    "type": "Auto",
    "price": 142,
    "coverage": "Comprehensive auto plan covering liability, theft, and collision",
    "region": "QC",
    "rating": 4.3,
    "term": "1 year",
    "benefits": ["Liability", "Theft", "Collision"],
    "giftcard": "upto 10",
    "icon": "https://www.tdinsurance.com/content/dam/tdinsurance/images/header-and-footer/tdi-desktop-logo-en.png",
    "url": "https://www.tdinsurance.com"
  },
  {
    "id": 73,
    "provider": "Allianz",
    "type": "Travel",
    "price": 78,
    "coverage": "Travel coverage with trip cancellation and emergency medical",
    "region": "MB",
    "rating": 4.4,
    "term": "1 month",
    "benefits": ["Trip Cancellation", "Medical Emergencies"],
    "giftcard": "upto 5",
    "icon": "https://imgs.search.brave.com/BpftFdOcsYQz8pDfZ2G59tC-MunruyagXbLoouES8GE/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMuc2Vla2xvZ28u/Y29tL2xvZ28tcG5n/LzAvMi9hbGxpYW56/LWJ1bGdhcmlhLWxv/Z28tcG5nX3NlZWts/b2dvLTY4NjkucG5n",
    "url": "https://www.allianz-assistance.ca"
  },
  {
    "id": 74,
    "provider": "Definity",
    "type": "Home",
    "price": 119,
    "coverage": "Comprehensive home insurance with theft, liability, and storm damage",
    "region": "PE",
    "rating": 4.3,
    "term": "1 year",
    "benefits": ["Theft", "Liability", "Storm Damage"],
    "giftcard": "upto 9",
    "icon": "https://s28.q4cdn.com/441925426/files/design/header-logo.png",
    "url": "https://www.definityfinancial.com"
  },
  {
    "id": 75,
    "provider": "TuGo",
    "type": "Travel",
    "price": 68,
    "coverage": "Travel insurance covering baggage loss, trip interruption, and emergencies",
    "region": "NS",
    "rating": 4.4,
    "term": "1 month",
    "benefits": ["Baggage Loss", "Trip Interruption", "Medical Emergencies"],
    "giftcard": "upto 5",
    "icon": "https://www.tugo.com/images/tugo_logo_en.svg",
    "url": "https://www.tugo.com"
  },

  ]
